# -*- coding: utf-8 -*-
"""Cleaning_missing_value and adding corrdinates

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKTQm2VS1Z4sHB-Jh2iACK17qZBRm1ZF
"""

import pandas as pd

# Load the dataset
file_path = '/content/cleaned_data_final1.csv'
cleaned_data = pd.read_csv(file_path)

# Display column names to ensure correct usage
column_names = cleaned_data.columns.tolist()
print("Column Names:\n", column_names)

# Dictionary of cities/airports with their coordinates
coordinates = {
    'Adelaide': {'Latitude': -34.9285, 'Longitude': 138.6007},
    'Brisbane': {'Latitude': -27.4698, 'Longitude': 153.0251},
    'Canberra': {'Latitude': -35.2809, 'Longitude': 149.1300},
    'Darwin': {'Latitude': -12.4634, 'Longitude': 130.8456},
    'Gold Coast': {'Latitude': -28.0167, 'Longitude': 153.4000},
    'Hobart': {'Latitude': -42.8821, 'Longitude': 147.3272},
    'Melbourne': {'Latitude': -37.8136, 'Longitude': 144.9631},
    'Newcastle': {'Latitude': -32.9283, 'Longitude': 151.7817},
    'Perth': {'Latitude': -31.9505, 'Longitude': 115.8605},
    'Sydney': {'Latitude': -33.8688, 'Longitude': 151.2093},
    'Wollongong': {'Latitude': -34.4278, 'Longitude': 150.8931},
    'Geelong': {'Latitude': -38.1499, 'Longitude': 144.3617},
    'Townsville': {'Latitude': -19.2589, 'Longitude': 146.8169},
    'Cairns': {'Latitude': -16.9203, 'Longitude': 145.7710},
    'Toowoomba': {'Latitude': -27.5606, 'Longitude': 151.9537},
    'Ballarat': {'Latitude': -37.5622, 'Longitude': 143.8503},
    'Bendigo': {'Latitude': -36.7570, 'Longitude': 144.2794},
    'Albury': {'Latitude': -36.0737, 'Longitude': 146.9135},
    'Launceston': {'Latitude': -41.4545, 'Longitude': 147.1374},
    'Mackay': {'Latitude': -21.1411, 'Longitude': 149.1860},
    'Rockhampton': {'Latitude': -23.3751, 'Longitude': 150.5100},
    'Bunbury': {'Latitude': -33.3271, 'Longitude': 115.6417},
    'Bundaberg': {'Latitude': -24.8662, 'Longitude': 152.3489},
    'Hervey Bay': {'Latitude': -25.2893, 'Longitude': 152.8209},
    'Wagga Wagga': {'Latitude': -35.1089, 'Longitude': 147.3707},
    'Coffs Harbour': {'Latitude': -30.2963, 'Longitude': 153.1141},
    'Gladstone': {'Latitude': -23.8480, 'Longitude': 151.2629},
    'Shepparton': {'Latitude': -36.3770, 'Longitude': 145.3992},
    'Port Macquarie': {'Latitude': -31.4333, 'Longitude': 152.9080},
    'Orange': {'Latitude': -33.2839, 'Longitude': 149.1001}
}

# Function to get coordinates
def get_coordinates(location):
    return coordinates.get(location, {'Latitude': None, 'Longitude': None})

# Add Latitude and Longitude columns using the correct column names
cleaned_data[['Departing_Latitude', 'Departing_Longitude']] = cleaned_data['departing_port'].apply(lambda x: pd.Series(get_coordinates(x)))
cleaned_data[['Arriving_Latitude', 'Arriving_Longitude']] = cleaned_data['arriving_port'].apply(lambda x: pd.Series(get_coordinates(x)))

# Save the updated dataset
cleaned_data.to_csv('/cleaned_data_with_coords.csv', index=False)

cleaned_data[['departing_port', 'Departing_Latitude', 'Departing_Longitude', 'arriving_port', 'Arriving_Latitude', 'Arriving_Longitude']].head()

import pandas as pd

# Load the dataset
file_path = '/cleaned_data_with_coords.csv'  # Update with the actual file path
cleaned_data = pd.read_csv(file_path)

# Check for missing values
missing_values = cleaned_data.isnull().sum()
print("Missing values in each column:\n", missing_values)

import pandas as pd

# Load the dataset containing airport coordinates
coordinates_file_path = '/content/AIRPORT.xlsx'
coordinates_data = pd.read_excel(coordinates_file_path)

# Assuming the coordinates dataset has columns named 'Airport', 'Latitude', 'Longitude'
# Display the first few rows to understand its structure
print("Coordinates Dataset:\n", coordinates_data.head())

# Rename columns for consistency if needed
coordinates_data.columns = ['Airport', 'Latitude', 'Longitude']

# Load your main dataset
main_file_path = '/cleaned_data_with_coords.csv'
main_data = pd.read_csv(main_file_path)

# Merge coordinates with main dataset
main_data = main_data.merge(coordinates_data, left_on='departing_port', right_on='Airport', how='left')
main_data = main_data.rename(columns={'Latitude': 'Departing_Latitude', 'Longitude': 'Departing_Longitude'})

main_data = main_data.merge(coordinates_data, left_on='arriving_port', right_on='Airport', how='left')
main_data = main_data.rename(columns={'Latitude': 'Arriving_Latitude', 'Longitude': 'Arriving_Longitude'})

# Drop the redundant 'Airport' columns from merging
main_data = main_data.drop(columns=['Airport_x', 'Airport_y'])

# Fill missing values with 0
main_data[['Departing_Latitude', 'Departing_Longitude', 'Arriving_Latitude', 'Arriving_Longitude']] = main_data[['Departing_Latitude', 'Departing_Longitude', 'Arriving_Latitude', 'Arriving_Longitude']].fillna(0)

# Check for missing values again
missing_values_after_update = main_data.isnull().sum()
print("Missing values after adding coordinates and filling with 0:\n", missing_values_after_update)

# Save the updated dataset
updated_file_path = '/cleaned_data_with_coords_update.csv'
main_data.to_csv(updated_file_path, index=False)
print(f"Updated dataset saved to: {updated_file_path}")

# Display the first few rows of the updated dataset
main_data.head()

# Check for missing values again
missing_values_after_update = main_data.isnull().sum()
print("Missing values after adding coordinates and filling with 0:\n", missing_values_after_update)



# This will download the file to your local machine
from google.colab import files
files.download('/cleaned_data_with_coords_update.csv')