# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKTQm2VS1Z4sHB-Jh2iACK17qZBRm1ZF
"""

import pandas as pd

# Load the cleaned dataset
file_path = '/content/cleaned_data_final.csv'
cleaned_data = pd.read_csv(file_path)

# Fill missing values in 'on_time_ratio' with the median value of the column
cleaned_data['on_time_ratio'].fillna(cleaned_data['on_time_ratio'].median(), inplace=True)

# Verify that there are no more missing values
print("Missing values after imputation:\n", cleaned_data.isnull().sum())

# Save the updated dataframe to a new file
cleaned_file_path = '/content/cleaned_data_final1.csv'
cleaned_data.to_csv(cleaned_file_path, index=False)

cleaned_file_path

from google.colab import files

# Download the file
files.download('cleaned_data_final1.csv')

